---
- hosts: webservers
  become: yes
  gather_facts: false
  remote_user: vagrant
  tasks:
    - name: install apache2
      apt:
        #update_cache: yes
        name: apache2
        state: present
    - name: start apache2 service
      service:
        name: apache2
        state: started
      ignore_errors: true
    - name: copy index.html file to webservers
      copy:
        src: index.html
        dest: /var/www/html
      tags: copy
    - name: copy files on remote machine
      copy:
        src: /home/vagrant/file1
        dest: /tmp
        remote_src: yes
    - name: create a file and change ownership
      file:
        path: /home/vagrant/data
        state: touch
        owner: root
        group: vagrant
        mode: 0777
      tags: file
      register: stdout
    - name: print previous tasks
      debug:
        msg: "{{stdout}}"

        
