---
- hosts: dbservers
  become: yes
  remote_user: vagrant
  tasks:
 
    - name: install apache2 in dbservers
      apt: 
       # update_cache: yes
        name: apache2
        state: present
    - name: start apache2 service
      service:
        name: apache2
        state: started
    - name: copy index.html file to deserver
      copy:
        src: index.html
        dest: /var/www/html
    - name: copy file to /tmp location
      copy:
        src: /home/vagrant/file2
        dest: /tmp
        remote_src: yes
    - name: create user and change ownership
      file:
        path: /home/vagrant/data
        state: touch
        owner: root
        group: vagrant
        mode: 0777
