---
- hosts: all
  become: yes
  tasks: 
    - name: install httpd
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"
    - name: install apache
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian" 

